### ISSUE TITLE
Empty list on php-ast(version30) + PHP7.1 + Windows

### ISSUE THREAD

**Issue by algo13** [nikic/php-ast#41] opened 2017-01-18 09:36 UTC
```php
<?php
// php-ast.dll(php_ast-20161209-7.1-ts-vc14-x64)

//var_dump(ast\parse_code('<?php list(,) = 1;', 35)); //< OK
var_dump(ast\parse_code('<?php list(,) = 1;', 30)); //< An "CLI Stop" dialog is displayed
```

```
>	php_ast-20161209-7.1-ts-vc14-x64.dll!ast_to_zval(_zval_struct * zv, _zend_ast * ast, __int64 version) line 487	C
 	php_ast-20161209-7.1-ts-vc14-x64.dll!ast_fill_children_ht(_zend_array * ht, _zend_ast * ast, __int64 version) line 418	C
 	php_ast-20161209-7.1-ts-vc14-x64.dll!ast_to_zval(_zval_struct * zv, _zend_ast * ast, __int64 version) line 568	C
 	php_ast-20161209-7.1-ts-vc14-x64.dll!ast_fill_children_ht(_zend_array * ht, _zend_ast * ast, __int64 version) line 418	C
 	php_ast-20161209-7.1-ts-vc14-x64.dll!ast_to_zval(_zval_struct * zv, _zend_ast * ast, __int64 version) line 568	C
 	php_ast-20161209-7.1-ts-vc14-x64.dll!zif_parse_code(_zend_execute_data * execute_data, _zval_struct * return_value) line 689	C
 	php_xdebug-2.5.0-7.1-vc14-x86_64.dll!00007ffa7c296621()	unknown
 	php7ts.dll!00007ffa631e9951()	unknown
 	php7ts.dll!00007ffa63279c8a()	unknown
 	php7ts.dll!00007ffa62e25114()	unknown
 	php_xdebug-2.5.0-7.1-vc14-x86_64.dll!00007ffa7c295f88()	unknown
 	php7ts.dll!00007ffa62e56dc1()	unknown
 	php7ts.dll!00007ffa62e5687e()	unknown
 	php7ts.dll!00007ffa62e56698()	unknown
 	php.exe!00007ff6a65a1dca()	unknown
 	php.exe!00007ff6a65a1566()	unknown
 	php.exe!00007ff6a65a2879()	unknown
```

**Comment by nikic** [comment] 2017-01-18 20:53
This looks like a duplicate of #36. Just released a new version with this fix.

**Closed by nikic** 2017-01-18 20:53 UTC

**Comment by algo13** [comment] 2017-01-19 12:24
@nikic Thanks for the released !!
Is it possible to release the DLL ?
