### ISSUE TITLE
ParseError messages emitted by ast\parse_code are slightly different for the first exception and subsequent exceptions

### ISSUE THREAD

**Issue by TysonAndre** [nikic/php-ast#79] opened 2017-09-17 22:08 UTC
Observed output: Depending on the calling context, the thrown ParseError may say ` unexpected 'return'`, the other says ` unexpected return` (without single quotes).

My guess is that it's related to the presence of a closure.
**EDIT: No, the first call is different from the remaining calls**

This happens in php 7.1.8, PHP 7.2.0RC2, and 7.0.23 (NTS builds)
Version used: 4e5d78 (current master branch). May affect all versions, haven't checked.

## Example:

```php
<?php

$src = '<'.'?php

function test_missing_semicolon() : string {
     $x = []
     return
}
';

$path = 'missing/path.php';

function parse_in_fn() {
    global $src, $path;
    try {
        \ast\parse_code($src, 50, $path);
    } catch (\Throwable $e) {
        echo "Threw exception in function\n";
        echo $e . "\n";
    }
}
function main() {
    $parse_in_closure = function() {
        global $src, $path;
        try {
            \ast\parse_code($src, 50, $path);
        } catch (\Throwable $e) {
            echo "Threw exception in closure\n";
            echo $e . "\n";
        }
    };

    parse_in_fn();
    $result = $parse_in_closure();
}
main();
```

## Observed output: 
One says ` unexpected 'return'`, the other says ` unexpected return` (without single quotes)

```
$ ~/php-7.1.8-fast-nts-install/bin/php inconsistent.php
Threw exception in function
ParseError: syntax error, unexpected 'return' (T_RETURN) in missing/path.php:5
Stack trace:
#0 /path/to/inconsistent.php(16): ast\parse_code('<?php\n\nfunction...', 50, 'missing/path.ph...')
#1 /path/to/inconsistent.php(33): parse_in_fn()
#2 /path/to/inconsistent.php(36): main()
#3 {main}
Threw exception in closure
ParseError: syntax error, unexpected return (T_RETURN) in missing/path.php:5
Stack trace:
#0 /path/to/inconsistent.php(26): ast\parse_code('<?php\n\nfunction...', 50, 'missing/path.ph...')
#1 /path/to/inconsistent.php(34): {closure}()
#2 /path/to/inconsistent.php(36): main()
#3 {main}
```

## Motivations

Want predictable output. Deduplicating based on $e->getMessage() should work intuitively.

## Workaround

From PHP: Manually call ast\parse_code() from within a closure all of the time? (Seems to require putting try{} catch{} in the closure, not just ast\parse_code)

Not familiar enough with php-src to know how to change this.

**Comment by TysonAndre** [comment] 2017-09-17 22:23
My earlier guess was wrong. It seems like the first error message from `ast\parse_code` is slightly different then the remaining ones.

```
<?php

$src = '<'.'?php

function test_missing_semicolon() : string {
     $x = []
     return
}
';

$path = 'missing/path.php';

function parse_in_fn() {
    global $src, $path;
    try {
        \ast\parse_code($src, 50, $path);
    } catch (\Throwable $e) {
        echo "Threw exception in function\n";
        echo $e . "\n";
    }
}
function main() {
    $parse_in_closure = function() {
        global $src, $path;
        try {
            \ast\parse_code($src, 50, $path);
        } catch (\Throwable $e) {
            echo "Threw exception in closure\n";
            echo $e . "\n";
        }
    };
    // Okay, the *first* parse error seems to have different formatting then the remaining ones.
    // So doing this acts as a workaround.
    try {
        \ast\parse_code('<' . '?php s', 50);
        throw new \RuntimeError('should be invalid');
    } catch (\ParseError $e) {
        // Workaround.
    }

    parse_in_fn();
    $result = $parse_in_closure();
}
main();
```

The above snippet based on the original snippet has consistent error messages

**Comment by nikic** [comment] 2017-09-18 14:15
This is probably caused by incorrect parse_error clearing. It's only reset in https://github.com/php/php-src/blob/beb9295790c32dde5364d8ce03dde7848641c7f1/main/main.c#L1220, which happens only on an uncaught parse error. We should be clearing it in zenderror() instead. Probably this issue can also be reproduced without the ast extension.

**Comment by nikic** [comment] 2017-09-24 06:57
Upstream bug report https://bugs.php.net/bug.php?id=75252 fixed by https://github.com/php/php-src/commit/73d6456d7d6be62340b3607805a45cbf420c1cb8.

**Closed by nikic** 2017-09-24 06:57 UTC

**Comment by TysonAndre** [comment] 2017-09-24 06:58
Thanks!
